# __  __ _   _
#|  \/  | \ | |
#| \  / |  \| |  Michael Neuper
#| |\/| | . ` |  https://michaelneuper.com
#| |  | | |\  |  https://github.com/michaelneuper
#|_|  |_|_| \_|
#
## FIRST LINE/ROW
# First param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = " repo: "
read_only =  " 🔒 "
read_only_style = "red"

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "bold red"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "✘"
conflicted = "="
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"

# Command duration
[cmd_duration]
min_time = 1
show_milliseconds = false
format = "took [$duration]($style)"
disabled = true

## SECOND LINE/ROW
# Somethere at the beginning
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

[character]  # Tells whether last command was successful or not
success_symbol = " [❯](bold green)"
error_symbol = " [✖ ](bold red)"
vicmd_symbol = "[❮](bold green)"

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
