#! /bin/sh
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends --backend glx --xrender-sync-fence & # for nvidia gpu
dunst --startup-notification true &
emacs --daemon &
onedriver $HOME/onedrive &

#### MONITORS ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

#### BSPWM coloring ####
bspc config normal_border_color     "#abb2bf"
bspc config active_border_color     "#c678dd"
bspc config focused_border_color    "#56b6c2"
bspc config presel_feedback_color   "#61afef"
bspc config urgent_border_color     "#e06c75"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Qalculate-gtk state=floating
bspc rule -a "VirtualBox Manager" state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Places state=floating
